export const LOADING_LIST_CHATS         = "LOADING_LIST_CHATS";
export const LOADED_LIST_CHATS_SUCCESS  = "LOADED_LIST_CHATS_SUCCESS";
export const LOADED_LIST_CHATS_FAIL     = "LOADED_LIST_CHATS_FAIL";