export const LOADING_LIST_CHATS             = "LOADING_LIST_CHATS";
export const LOADED_LIST_CHATS_SUCCESS      = "LOADED_LIST_CHATS_SUCCESS";
export const LOADED_LIST_CHATS_FAIL         = "LOADED_LIST_CHATS_FAIL";
export const LOADING_CHAT_HISTORY           = "LOADING_CHAT_HISTORY";
export const LOADED_CHAT_HISTORY_SUCCESS    = "LOADED_CHAT_HISTORY_SUCCESS";
export const LOADED_CHAT_HISTORY_FAIL       = "LOADED_CHAT_HISTORY_FAIL";